package Pertemuan13.Tugas.MateriGUI;

import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Adji Pangestu
 */
public class BukuAlamatGUI extends javax.swing.JFrame {

    /**
     * Creates new form BukuAlamatGUI
     */
    public BukuAlamatGUI() {
        initComponents();
    }

    public void Hapus() {
        kolomNama.setText(null);
        kolomAlamat.setText(null);
        kolomTelepon.setText(null);
        kolomEmail.setText(null);
    }

    public void Simpan() {
        if (kolomNama.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Kolom Nama Kosong, Silahkan isi Nama dengan benar", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (kolomAlamat.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Kolom Alamat Kosong. Silahkan isi Alamat dengan benar", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (kolomTelepon.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Kolom Telepon Kosong. Silahkan isi Telepon dengan benar", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (kolomEmail.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Kolom Email Kosong. Silahkan isi Email dengan benar", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else {
            try (FileOutputStream file = new FileOutputStream("Database.dat", true)) {
                String nama = kolomNama.getText() + "\t";
                String alamat = kolomAlamat.getText()+ "\t";
                String telepon = kolomTelepon.getText()+ "\t";
                String email = kolomEmail.getText()+ "\t";

                file.write(nama.getBytes());
                file.write(alamat.getBytes());
                file.write(telepon.getBytes());
                file.write(email.getBytes());
                file.close();
                JOptionPane.showMessageDialog(null, "Data Berhasil Di Simpan!");
            } catch (IOException e) {
                e.printStackTrace();

            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundBelakang = new javax.swing.JPanel();
        BackgroundAtas = new javax.swing.JPanel();
        SubJudul = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        labelAlamat = new javax.swing.JLabel();
        labelTelepon = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        buttonHapus = new java.awt.Button();
        buttonSimpan = new java.awt.Button();
        kolomNama = new javax.swing.JTextField();
        kolomAlamat = new javax.swing.JTextField();
        kolomTelepon = new javax.swing.JTextField();
        kolomEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Buku Alamat");
        setBackground(new java.awt.Color(255, 255, 255));

        BackgroundBelakang.setBackground(new java.awt.Color(255, 255, 255));

        BackgroundAtas.setBackground(new java.awt.Color(153, 153, 153));

        SubJudul.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        SubJudul.setForeground(new java.awt.Color(255, 255, 255));
        SubJudul.setText("Isi Data Buku Alamat");

        javax.swing.GroupLayout BackgroundAtasLayout = new javax.swing.GroupLayout(BackgroundAtas);
        BackgroundAtas.setLayout(BackgroundAtasLayout);
        BackgroundAtasLayout.setHorizontalGroup(
            BackgroundAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundAtasLayout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(SubJudul)
                .addGap(73, 73, 73))
        );
        BackgroundAtasLayout.setVerticalGroup(
            BackgroundAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundAtasLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(SubJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        labelNama.setText("Nama     ");

        labelAlamat.setText("Alamat   ");

        labelTelepon.setText("Telepon ");

        labelEmail.setText("E-mail    ");

        buttonHapus.setBackground(new java.awt.Color(244, 67, 54));
        buttonHapus.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        buttonHapus.setForeground(new java.awt.Color(255, 255, 255));
        buttonHapus.setLabel("HAPUS");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        buttonSimpan.setBackground(new java.awt.Color(76, 175, 80));
        buttonSimpan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        buttonSimpan.setForeground(new java.awt.Color(255, 255, 255));
        buttonSimpan.setLabel("SIMPAN");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        kolomNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolomNamaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackgroundBelakangLayout = new javax.swing.GroupLayout(BackgroundBelakang);
        BackgroundBelakang.setLayout(BackgroundBelakangLayout);
        BackgroundBelakangLayout.setHorizontalGroup(
            BackgroundBelakangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundBelakangLayout.createSequentialGroup()
                .addComponent(BackgroundAtas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(BackgroundBelakangLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(BackgroundBelakangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundBelakangLayout.createSequentialGroup()
                        .addComponent(buttonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                        .addComponent(buttonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackgroundBelakangLayout.createSequentialGroup()
                        .addGroup(BackgroundBelakangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelAlamat)
                            .addComponent(labelTelepon)
                            .addComponent(labelEmail)
                            .addComponent(labelNama))
                        .addGap(18, 18, 18)
                        .addGroup(BackgroundBelakangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackgroundBelakangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(kolomAlamat)
                                .addComponent(kolomNama)
                                .addComponent(kolomTelepon, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))
                            .addComponent(kolomEmail))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BackgroundBelakangLayout.setVerticalGroup(
            BackgroundBelakangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundBelakangLayout.createSequentialGroup()
                .addComponent(BackgroundAtas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(BackgroundBelakangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kolomNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNama))
                .addGap(17, 17, 17)
                .addGroup(BackgroundBelakangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAlamat)
                    .addComponent(kolomAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(BackgroundBelakangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTelepon)
                    .addComponent(kolomTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(BackgroundBelakangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEmail)
                    .addComponent(kolomEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(BackgroundBelakangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        buttonHapus.getAccessibleContext().setAccessibleParent(BackgroundAtas);
        buttonSimpan.getAccessibleContext().setAccessibleParent(BackgroundAtas);
        kolomNama.getAccessibleContext().setAccessibleParent(BackgroundAtas);
        kolomAlamat.getAccessibleContext().setAccessibleParent(BackgroundAtas);
        kolomTelepon.getAccessibleContext().setAccessibleParent(BackgroundAtas);
        kolomEmail.getAccessibleContext().setAccessibleParent(BackgroundAtas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundBelakang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundBelakang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        // TODO add your handling code here:
        Simpan();
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        // TODO add your handling code here:
        Hapus();
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void kolomNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolomNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kolomNamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BukuAlamatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BukuAlamatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BukuAlamatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BukuAlamatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BukuAlamatGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundAtas;
    private javax.swing.JPanel BackgroundBelakang;
    private javax.swing.JLabel SubJudul;
    private java.awt.Button buttonHapus;
    private java.awt.Button buttonSimpan;
    private javax.swing.JTextField kolomAlamat;
    private javax.swing.JTextField kolomEmail;
    private javax.swing.JTextField kolomNama;
    private javax.swing.JTextField kolomTelepon;
    private javax.swing.JLabel labelAlamat;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelTelepon;
    // End of variables declaration//GEN-END:variables
}
